In [249]:
import pandas as pd
import pathlib
import glob
import os

In [250]:

#concate all text
path = "/Users/pr158admin/Downloads/US_VitalStatistics/"

print(path)
all_files = glob.glob(os.path.join(path, "*.txt"))
all_files
overdose_merge = pd.concat((pd.read_csv(f ,delimiter ="\t") for f in all_files))

/Users/pr158admin/Downloads/US_VitalStatistics/

In [251]:

overdose_merge.sample(10)

,Notes,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
2797,NaN,"Adair County, OK",40001.0,2003.0,2003.0,All other non-drug and non-alcohol causes,O9,227.0
1386,NaN,"Jackson County, KS",20085.0,2011.0,2011.0,All other non-drug and non-alcohol causes,O9,136.0
4349,NaN,"Laramie County, WY",56021.0,2009.0,2009.0,All other alcohol-induced causes,A9,13.0
4360,NaN,"Teton County, WY",56039.0,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,69.0
2385,NaN,"Hillsborough County, NH",33011.0,2007.0,2007.0,All other non-drug and non-alcohol causes,O9,2802.0
784,NaN,"Floyd County, GA",13115.0,2012.0,2012.0,All other alcohol-induced causes,A9,11.0
1832,NaN,"Itasca County, MN",27061.0,2004.0,2004.0,All other non-drug and non-alcohol causes,O9,472.0
2066,NaN,"Red Lake County, MN",27125.0,2013.0,2013.0,All other non-drug and non-alcohol causes,O9,51.0
2576,NaN,"Salem County, NJ",34033.0,2013.0,2013.0,All other non-drug and non-alcohol causes,O9,680.0
2209,NaN,"Phelps County, MO",29161.0,2009.0,2009.0,All other non-drug and non-alcohol causes,O9,393.0

In [252]:
#distinct values of columns
overdose_merge["Drug/Alcohol Induced Cause Code"].unique()

array(['O9', 'D1', 'D4', 'D2', 'D9', 'A9', 'A1', nan, 'D3'], dtype=object)

In [253]:
#filter the drug induced deaths
drug_code = ['D1','D2','D3','D4']
overdose_df = overdose_merge[overdose_merge["Drug/Alcohol Induced Cause Code"].isin(drug_code)]

In [254]:
overdose_df.sample(10)

,Notes,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
3044,NaN,"Mercer County, PA",42085.0,2004.0,2004.0,Drug poisonings (overdose) Unintentional (X40-...,D1,13.0
1507,NaN,"Harlan County, KY",21095.0,2010.0,2010.0,Drug poisonings (overdose) Unintentional (X40-...,D1,13.0
803,NaN,"Henry County, GA",13151.0,2009.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,17.0
3635,NaN,"Greenville County, SC",45045.0,2015.0,2015.0,Drug poisonings (overdose) Unintentional (X40-...,D1,100
3576,NaN,"Tarrant County, TX",48439.0,2003.0,2003.0,Drug poisonings (overdose) Suicide (X60-X64),D2,17.0
3120,NaN,"Bryan County, OK",40013.0,2012.0,2012.0,Drug poisonings (overdose) Unintentional (X40-...,D1,12.0
1338,NaN,"Scott County, IA",19163.0,2012.0,2012.0,Drug poisonings (overdose) Unintentional (X40-...,D1,22.0
595,NaN,"Manatee County, FL",12081.0,2006.0,2006.0,Drug poisonings (overdose) Suicide (X60-X64),D2,11.0
2438,NaN,"Passaic County, NJ",34031.0,2007.0,2007.0,Drug poisonings (overdose) Unintentional (X40-...,D1,28.0
322,NaN,"San Diego County, CA",6073.0,2004.0,2004.0,Drug poisonings (overdose) Unintentional (X40-...,D1,225.0

In [255]:
#write df to csv in the  repo

overdose_df.to_csv("overdose_df.csv", encoding="utf-8", index=False)

In [256]:
#filtering the states
states= ["FL","WA","TX","ME","WV","VT","AK","DC","UT","IL","LA","MD","OK"]
#overdose_df1 = overdose_df[overdose_df["County"].isin(states)]
overdose_final=overdose_df[overdose_df["County"].str.contains('|'.join(states))]
overdose_final.sample(10)

,Notes,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths
1809,NaN,"Montgomery County, MD",24031.0,2014.0,2014.0,Drug poisonings (overdose) Suicide (X60-X64),D2,12.0
665,NaN,"Santa Rosa County, FL",12113.0,2007.0,2007.0,Drug poisonings (overdose) Unintentional (X40-...,D1,20.0
3574,NaN,"Nueces County, TX",48355.0,2004.0,2004.0,Drug poisonings (overdose) Unintentional (X40-...,D1,18.0
3868,NaN,"Rutland County, VT",50021.0,2007.0,2007.0,Drug poisonings (overdose) Unintentional (X40-...,D1,12.0
4513,NaN,"King County, WA",53033.0,2015.0,2015.0,Drug poisonings (overdose) Undetermined (Y10-Y14),D4,10
3706,NaN,"Henderson County, TX",48213.0,2008.0,2008.0,Drug poisonings (overdose) Unintentional (X40-...,D1,10.0
1040,NaN,"Madison County, IL",17119.0,2010.0,2010.0,Drug poisonings (overdose) Unintentional (X40-...,D1,57.0
3243,NaN,"Tulsa County, OK",40143.0,2013.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,106.0
4077,NaN,"Pierce County, WA",53053.0,2007.0,2007.0,Drug poisonings (overdose) Unintentional (X40-...,D1,98.0
586,NaN,"Manatee County, FL",12081.0,2005.0,2005.0,Drug poisonings (overdose) Unintentional (X40-...,D1,43.0

In [257]:
# new=overdose_final["County"].str.split(",", n=1, expand = True).copy(deep=True)
# df[['First','Last']] = df.Name.str.split(expand=True)
#overdose_final.County.str.split(",", n=1, expand = True).
overdose_copy=overdose_final.copy()
overdose_copy[['County', 'State']]= overdose_final.County.str.split(",", n=1, expand = True)

In [258]:
overdose_copy['County']=overdose_copy['County'].str.lower()

In [259]:
overdose_copy

,Notes,County,County Code,Year,Year Code,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths,State
90,NaN,anchorage borough,2020.0,2009.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,46.0,AK
91,NaN,anchorage borough,2020.0,2009.0,2009.0,Drug poisonings (overdose) Suicide (X60-X64),D2,11.0,AK
97,NaN,fairbanks north star borough,2090.0,2009.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,16.0,AK
102,NaN,kenai peninsula borough,2122.0,2009.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,11.0,AK
108,NaN,matanuska-susitna borough,2170.0,2009.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,15.0,AK
...,...,...,...,...,...,...,...,...,...
4439,NaN,putnam county,54079.0,2013.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,11.0,WV
4441,NaN,raleigh county,54081.0,2013.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,33.0,WV
4451,NaN,wayne county,54099.0,2013.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,17.0,WV
4456,NaN,wood county,54107.0,2013.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,16.0,WV
4458,NaN,wyoming county,54109.0,2013.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,14.0,WV

In [260]:
# overdose_final["States"]=new[1].copy(deep=True)

In [263]:
overdose_copy.drop(['Notes','Year Code'], axis=1)

,County,County Code,Year,Drug/Alcohol Induced Cause,Drug/Alcohol Induced Cause Code,Deaths,State
90,anchorage borough,2020.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,46.0,AK
91,anchorage borough,2020.0,2009.0,Drug poisonings (overdose) Suicide (X60-X64),D2,11.0,AK
97,fairbanks north star borough,2090.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,16.0,AK
102,kenai peninsula borough,2122.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,11.0,AK
108,matanuska-susitna borough,2170.0,2009.0,Drug poisonings (overdose) Unintentional (X40-...,D1,15.0,AK
...,...,...,...,...,...,...,...
4439,putnam county,54079.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,11.0,WV
4441,raleigh county,54081.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,33.0,WV
4451,wayne county,54099.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,17.0,WV
4456,wood county,54107.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,16.0,WV
4458,wyoming county,54109.0,2013.0,Drug poisonings (overdose) Unintentional (X40-...,D1,14.0,WV